### ISSUE TITLE
Mention in the component description whether it depends on material-ui

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/components#11]

**Comment by HrushikeshBodas** [comment]
Shall I take this up? @helfi92

**Comment by helfi92** [comment]
Go for it. Thank you @HrushikeshBodas.

**Comment by HrushikeshBodas** [comment]
> 
> 
> Go for it. Thank you @HrushikeshBodas.

Where do I need to make the changes? In the component files or somewhere else?

**Comment by helfi92** [comment]
Changing the component files sounds good to me.

**Comment by isaeef** [comment]
@helfi92  is it still open ?

**Comment by helfi92** [comment]
Yes, it is. Go for it :)

**Comment by vishakhanihore** [comment]
@helfi92 Can I work on it?
