### ISSUE TITLE
Use Material for low-level UI interactions

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/components#3]
Low-level UI interactions should be related to some framework, and we have picked material. We should mention that somewhere.

**Comment by vishakhanihore** [comment]
What would be best location to mention the following ?

**Comment by divyanshu-rawat** [comment]
Hey @helfi92 is it open to work on ?

**Comment by helfi92** [comment]
Ah, that was previously resolved in https://github.com/mozilla-frontend-infra/components/commit/6f2da76e4a988960db31eb850574be9216aa25fd.
