### ISSUE TITLE
Add a markdown preview component

### ISSUE THREAD

**Issue by helfi92** [mozilla-frontend-infra/components#39]

**Comment by projectyang** [comment]
Would it be appropriate for me to add the black/white colour codes in the palette object?

`
palette: {
    error: {
      ...red,
      ...error,
    },
    black: '#000',
    white: '#fff',
  },...`

**Comment by helfi92** [comment]
The [default theme](https://material-ui.com/customization/default-theme/) seem to have both black and white defined under `theme.palette.common`. I'm not sure if this was introduced recently though. Can you check if it's there in v3?
