### ISSUE TITLE
Update the markdown-it version to remove the Vulnerability

### ISSUE THREAD

**Issue by vishakhanihore** [mozilla-frontend-infra/components#53]
SInce markdown-it@8.4 is vulnerable. I propose to update the following to a new and secure version

**Comment by vishakhanihore** [comment]
@helfi92 If this is a valid clause, I would love to work on it. Thanks

**Comment by vishakhanihore** [comment]
Sure I will

**Comment by vishakhanihore** [comment]
@helfi92 Should I also update the `yarn` version with this issue?

**Comment by helfi92** [comment]
Good catch. I created https://github.com/mozilla-frontend-infra/components/pull/58 :)
